### ISSUE TITLE
Suggestions for the structure of the smart contract

### ISSUE THREAD

**Issue by willjgriff** [1Hive/token-request-app#10]
I don't think it's necessary for the token-request-app to have a reference to the voting app contract as we can use the forwarding functionality within Aragon. In this case there would be one `request()` function that accepts `depositToken`, `depositAmount`, `mintAmount`, `receiverAddress` that transfers the tokens from the `receiverAddress` and mints and sends requested tokens back to the `receiverAddress` in one transaction. Then we can give the permission to execute the function to a forwarding app such as the voting app. When attempting to execute this function the Aragon API will prompt and automatically create a vote to execute the `request()` function when the vote is over if it passes. 

This means for token requests made for ERC20 tokens the user should only have to do 1 transaction, instead of 2. However, for payments in ETH, I think the user will have to send ETH ahead of when whatever forwarding contract executes the `request()` function, eg before the end of a vote. I would suggest using a `payable` fallback function that records the sender of the ETH and updating the `refund()` function to allow whoever sent the ETH to withdraw it at any time. The `request()` function would then check the ETH had been received and prevent withdrawal once `request()` has been executed. 

Also, as the transfer of ERC20 tokens is done atomically in the `request()` function you no longer need to include the withdrawal of ERC20 tokens in the `refund()` function.

**Comment by lkngtn** [comment]
I'm not sure I follow the implications of this (setting aside the eth versus erc20 issue for a second). 

The flow should be: 
1) user deposits payment (eth or erc20) into the token request app along with a request for some amount of tokens to be minted for them. 
2) depending on permissions, the vote (or perhaps some other form of authorization will occur through forwarding), but if it the action executes it should first validate that the payment is in the token request app and transfer it to a vault, then mint tokens for the requestor from the token manager app. It should fail if the requestors payment is not there. 
3) a user should be able to withdraw their payment at any time, but if they do so before the tokens are minted, that action should fail to execute

Is this consistent with what you are describing?

Or are you saying we don't need the user to deposit tokens at all, instead we have them pre-authorize a transfer of some amount of tokens and validate that that transfer happens before minting?

**Comment by rperez89** [comment]
Maybe i am not understanding something, but how can you with the forwarder hold the tokens in escrow until the vote ends in only one transaction?

**Comment by fabriziovigevani** [comment]
> Also, as the transfer of ERC20 tokens is done atomically in the request() function you no longer need to include the withdrawal of ERC20 tokens in the refund() function.

I think the main issue here would be that the ERC20 token is not withheld by the token request app until the outcome of the vote or until the user requests the refund.
The ERC20 transfer would materialize only when the voting passes, but maybe this could be another approach? 
In either case i think we´ll have to make it consistent between ETH and ERC20.

**Comment by willjgriff** [comment]
> Is this consistent with what you are describing?

1. ERC20 tokens don't need to be deposited in the app, they just need to be approved by the user for the app to spend (which is necessary for either approach) before calling `request()`. ETH does need to be deposited before calling `request()`. 

2. `request()` is called by a forwarder, eg the voting app. If the payment is an ERC20 token, the app attempts to transfer the tokens using `transferFrom()` from the `receiverAddress` to the vault then mints the tokens and transfers them to the `receiverAddress`, if `transferFrom()` fails, so does minting the tokens. If the payment is in ETH it checks the ETH has been deposited by the `receiverAddress`, transfers it to the vault and mints the tokens.

3. A user paying ERC20 tokens can remove their approval for the app to spend them, preventing the `transferFrom()` call from executing and the app from minting the tokens. A user paying with ETH must call the `refund()` function to return their ETH to them.

> Or are you saying we don't need the user to deposit tokens at all, instead we have them pre-authorize a transfer of some amount of tokens and validate that that transfer happens before minting?

Yes that's what I'm suggesting for ERC20 tokens. As it requires one less transaction for them.

> Maybe i am not understanding something, but how can you with the forwarder hold the tokens in escrow until the vote ends in only one transaction?

They are not held in escrow, so the user can cancel their request during a vote by removing their approval. It appears this is also the case with the current `refund()` process. A user can choose not to mint tokens after the voting process is over and instead refund them.

> I think the main issue here would be that the ERC20 token is not withheld by the token request app until the outcome of the vote or until the user requests the refund.

Why does the app need to withhold the tokens if the user can refund them instead of minting them at the end of a vote?

> The ERC20 transfer would materialize only when the voting passes, but maybe this could be another approach?

This is what I'm suggesting. Using `transferFrom()`

> In either case i think we´ll have to make it consistent between ETH and ERC20.

Personally I think if one less transaction can be made when converting ERC20 tokens the lack of consistency is worth the increased usability. Note that 2 transactions will be required for each of ETH and ERC20 then. `approve()` (on the token they wish to part with) and `request()` (via a forwarder on the app) for ERC20. `deposit()` (on the app) and `request()` (via a forwarder on the app) for ETH.

**Comment by fabriziovigevani** [comment]
Yes actually makes sense.

What's more we wouldn't have to implement the voting creation and instead leverage the forwarding implementation and agree that more usability is worth the less consistency in this case.

It's more clear now thanks!

**Comment by facuspagnuolo** [comment]
@willjgriff just a few questions to see if I understand correctly, please let me know if I'm missing something... 

1. Who should be responsible for creating a new vote for each new request? 

2. IMHO, I think having different ways to handle requests depending on which token the user is paying with could be cumbersome, in terms of security and in terms of ux.

**Comment by willjgriff** [comment]
> 1. Who should be responsible for creating a new vote for each new request?

The Aragon API is responsible for creating a new vote, provided the Voting app is granted the permission to execute `requestTokens()`

> 2. IMHO, I think having different ways to handle requests depending on which token the user is paying with could be cumbersome, in terms of security and in terms of ux.

It depends on if the user is using ETH directly or ERC20 tokens, it doesn't vary for each ERC20 token. Can you be more specific regarding security risks? As for UX, when the user clicks to request tokens, if the user opts for ETH they could be prompted to execute 2 transactions in a row, one to call `depositEth()` with the ETH value and another to call/forward the `requestTokens()` function. If the user opts for ERC20 they could also be prompted to execute 2 transactions in a row, one to call `approve()` and one to call/forward the `requestTokens()` function.

**Comment by willjgriff** [comment]
To clarify, if we're interested in the above approach, the functions would be something like:

`depositEth()` which is payable and should also be callable from the fallback function
`refundEth()` which returns any Eth deposited by the calling address
`requestTokens(depositToken, depositAmount, mintAmount, receiverAddress)` for which the permission will be granted to the voting (or other forwarding) app and will move payment of ETH or ERC20 to the Vault and mint and send the requested number of tokens to the `receiverAddress`.

It should be noted that the permission for the `requestTokens()` function must be granted to a secure forwarder as soon as the app is deployed. If it isn't there is risk that someone could call `requestTokens()` minting huge amounts for next to nothing messing up the finances in the DAO.

**Comment by facuspagnuolo** [comment]
I see. Regarding the vote creation, I don’t follow what you mean with the Aragon API, an EOA should trigger that right? If so, how is supposed to be?

**Comment by willjgriff** [comment]
> Regarding the vote creation, I don’t follow what you mean with the Aragon API, an EOA should trigger that right? If so, how is supposed to be?

https://hack.aragon.org/docs/forwarding-intro

Basically when you try to execute a function through the Aragon API it checks if the address attempting it has permission to execute it, if not it then checks if the permission is granted to a forwarding contract address, if it is, and `canForward(senderAddress)` on the forwarder returns true then it will execute `forward(evmScript)` on the forwarder. In the Voting apps case this will create a vote which if successful will execute the previously specified `evmScript`.

Note that since an EOA is not executing the `requestTokens(depositToken, depositAmount, mintAmount, receiverAddress)` function, it is a forwarder that does, we must pass as an argument the `receiverAddress` that would otherwise have been referred to with `msg.sender`

**Comment by facuspagnuolo** [comment]
> Can you be more specific regarding security risks? 

Simply because you're increasing the attack surface if you need to handle that with two different functions.

> As for UX, when the user clicks to request tokens, if the user opts for ETH they could be prompted to execute 2 transactions in a row, one to call `depositEth()` with the ETH value and another to call/forward the `requestTokens()` function. If the user opts for ERC20 they could also be prompted to execute 2 transactions in a row, one to call `approve()` and one to call/forward the `requestTokens()` function.

That's my point, I thought you were saying this could be done in one transaction and I wasn't seeing how. Based on your comment, you meant the user will need to execute two transactions, am I right?
Besides, the user shouldn't be calling the `requestTokens()` function, the voting app should be the one calling it, although any voter should be able to trigger that action once the vote has passed, do you agree?

> Note that since an EOA is not executing the `requestTokens(depositToken, depositAmount, mintAmount, receiverAddress)` function, it is a forwarder that does, we must pass as an argument the `receiverAddress` that would otherwise have been referred to with `msg.sender`

I agree with this, but I didn't refer to the `requestTokens()` function, the missing point here is the vote creation. Whether or not there is a single entry point for users to deposit/approve their tokens signaling their interest to receive a certain amount of tokens minted, the vote creation must occur somewhere, and I thought it was a good solution to do it at the same time users deposit/approve their tokens (ETH or ERC20) in the app for it.

**Comment by lkngtn** [comment]
Summarizing my understanding of this discussion so far:
**Current implementation:**
- Users must deposit tokens or Ether into the token request app before making a request. 
- This requires 2 transaction (transfer, forward request) for Ether, and 3 (approve, transfer, forward request) for tokens. 
- Advantages are that we have essentially the same process for both Ether and Tokens, making the flow intuitive to communicate. 

**Will's proposal:**
- Users must deposit ether but are only require to approve token transfers. 
- This requires 2 transactions (transfer, forward request) for Ether, and 2 (approve, forward request) for tokens. 
- If the vote fails and the user was using tokens they also wouldn't need to call refund to get their payment back
- The advantage here is that we are reducing the number of transactions required by (atleast) 1 when a user is using tokens rather than Ether. 

While I generally would love to reduce the number of transactions (as it represents both ux friction and actual cost to the user), I think that in this case I lean toward the initial approach because it feels simpler to communicate what is happening. I think it is also a security benefit for the user to transfer and use the approval immediately. 

Consider the following situation. A user approves the token request to transfer some amount of DAI but does not execute the transfer. The members decline the request. The token request still has approval to take up to the amount of DAI that was approved, and it is an upgradeable contract. The members of the organization can upgrade the contract in the future and use it to steal funds from anyone who had previously requested tokens but never rescinded the approval. (And from a UX perspective, for the same reason that we are proposing this in the first place, the user is not likely think about making an additional transaction to rescind the approval.) 

On the other hand, if we go with the first implementation, the user is prompted to approve the tokens and immediately uses the approval amount up by transferring those tokens to the token request app. They can call refund at any time to get their tokens back, **and if their request is denied they are very likely to take action to retrieve their tokens.** 

The security model for the user is similar assuming they are paying attention and following best practices like rescinding the approval... but I think the first approach encourages behavior which is safer.

**Comment by willjgriff** [comment]
I would also like to mention the first approach require's building an evmScript in the request() function, which requires assembly. And it would require coupling the token-request-app to the Voting app, preventing alternative uses in the future via other forwarders, eg with an alternative voting app or the tokenManager (which would allow anyone with a membership token to execute the requestTokens() function for example). So ultimately the first approach will be less extensible and require more code.

**Comment by lkngtn** [comment]
Per our call it sounds like the way forward is to adopt the strategy described by will in https://github.com/1Hive/token-request-app/issues/10#issuecomment-501476931

But require uses to deposit tokens into the token request app to avoid having a hanging approval even if it means having 1 additional transaction for users.

**Comment by rperez89** [comment]
closed by #16
