### ISSUE TITLE
Design

### ISSUE THREAD

**Issue by rperez89** [1Hive/token-request-app#13]

**Comment by rperez89** [comment]
https://www.figma.com/file/NQA4OVNEWEFtWKWLK8B6gj/Untitled?node-id=16%3A1186

**Comment by rperez89** [comment]
<img width="890" alt="Screen Shot 2019-07-29 at 12 29 55 AM" src="https://user-images.githubusercontent.com/11763623/62020159-2840ee00-b198-11e9-930f-14758c4437a1.png">

<img width="887" alt="Screen Shot 2019-07-29 at 12 31 31 AM" src="https://user-images.githubusercontent.com/11763623/62020186-44448f80-b198-11e9-9c6e-496d313de721.png">

**Comment by lkngtn** [comment]
> https://www.figma.com/file/NQA4OVNEWEFtWKWLK8B6gj/Untitled?node-id=16%3A1186

Getting a 404 on this

**Comment by lkngtn** [comment]
In the table, wondering if we should have two sections:

1) Pending requests that the user has made (including the status and the ability to cancel/withdraw before or after approval)
2) Past and Pending requests that have been made to the org

The thinking being that it's helpful for user to be able to see the types of requests that have been approved previously. 

From a priority perspective, the first part is more important than the second, the MVP is really that is if someone makes a request and it gets declined, they are able to come back and withdraw their payment. 

Other minor notes:
- We should decided whether the deposit token is a global parameter set by the the org, or something that users can simply define. (EG you can pay in DAI or ETH or XYZ token). Making it a global parameter I think makes the flow a bit more intuitive and seems generally quite practical (org is raising in DAI or ETH or one specific token) which feels pretty common, but having user select a token at time of request is certainly more flexible. (though it may complicate the UX and introduce potential security issues since the token contract we interact with won't have been pre-approved by the org). 
- We should remove the dash in the app name on the menu
- We should consider what the UX would look like if we decided to implement #19

**Comment by rperez89** [comment]
yes i was wondering if we want to have a history of request, that could be useful, what about having two tables the top one with the active requests and a bottom one with the history? if there are not active request we will show only one.

And sure we should add a status for each line , the three dots is where i was thinking to add the options to Execute/Refund

**Comment by rperez89** [comment]
> https://www.figma.com/file/NQA4OVNEWEFtWKWLK8B6gj/Untitled?node-id=16%3A1186

now it should work
