### ISSUE TITLE
Initial Impressions: Contract

### ISSUE THREAD

**Issue by yeqbfgxjiq** [1Hive/token-request-app#54]
Initially there are 3 things that were not clear:
- the `MAX_ACCEPTED_DEPOSIT_TOKENS` and `MAX_ADDRESS_TOKEN_REQUEST_IDS constants`
- the `TokenRequest` struct supporting multiple collateral tokens while also having no fixed exchange rate between the DAO's membership token and tributes
- the structure of `nextTokenRequestId`, `tokenRequests`, and `addressTokenRequestIds`

<br>

### `MAX_ACCEPTED_DEPOSIT_TOKENS` and `MAX_ADDRESS_TOKEN_REQUEST_IDS constants`

Are these parameters that the DAO developer/admin can configure via the CLI?

~~Does `MAX_ACCEPTED_DEPOSIT_TOKENS` cap the amount of tokens any user can request in a single TokenRequest? If so, this would be a good param to either encourage more diverse participation and/or cap any influence whales might have. Each DAO should be able to configure this param themselves though.~~
EDIT: after going through the contract to see if I could update it to a single token model, I found that actually `MAX_ACCEPTED_DEPOSIT_TOKENS` is the max amount of tokens that can be set as valid deposit tokens.

Does `MAX_ADDRESS_TOKEN_REQUEST_IDS` limit the amount of TokenRequests that an account can create? If so, 100 is A LOT. Why not just set it to 1, or maybe even 5? Again, the DAO should be able to configure this param.

<br>

### Supporting multiple collateral tokens while also having no fixed exchange rate between the DAO's membership token and tributes

I don't understand this. If there is a good reason please let me know. 

As is, it seems like it introduces a lot of complexity for users. First, The UX would be a lot smoother if the DAO just chose 1 token to accept as tribute. Then the cognitive overhead for the user and the DAO members is low.
- seems like this would be easy to do by just changing the `acceptedDepositTokens` variable from an array to a single value `acceptedDepositToken`. Then the `addToken()` and `removeToken()` functions would be replaced by a single `updateToken()` function that changes the address in storage.
 
Also, there needs to be a fixed direct exchange rate for the collateral token vs the DAO's membership/voting token. If there is not, then EVERY TIME someone makes a token request the DAO members will have to evaluate their value add vs the tribute, come to consensus, vote, etc... We want to reduce the complexity and time spent on governance, not increase it. This would be a nightmare to be in the middle of and could easily create lots of tension and disagreement within the org
- Example: Why did Bob get in for 5, but Alice had to pay 20?! Alice is awesome. WTF. Bob and his friends are assholes and a cartel runs the DAO. Let's fork!

<br>

### The structure of `nextTokenRequestId`, `tokenRequests`, and `addressTokenRequestIds`

I _think_ I actually kind of understand this now, but it was not at all intuitive on the first 2 read throughs. Essentially, you'd think that we could just map an address to a TokenRequest struct, but that would limit the amount of token requests a user can make to 1 at a time (which I actually think would be better). IF we want to support multiple token requests by a user at a single time (which it seems like we do for some reason?), then we need a way to identify which token requests are being submitted to a vote and which can be withdrawn. This is why there is a mapping from a user's address to an array of tokenRequstIds, then that tokenRequestId maps to an actual TokenRequest struct. Is that correct?

**Comment by willjgriff** [comment]
1) We have these hard maximums to prevent griefing attacks. Since we iterate over arrays, there is risk that if these arrays reach a size that is too big to iterate over within the gas limit, however unlikely, the contract will become locked. Personally I think that as long as after testing we determine these maximums are on the lower end of what fits in the block limit and the upper end of what users want then I don't think they should be configurable to prevent mistakes by users that expose the contract to being locked.

2) a) Personally I don't think the cognitive overhead of allowing multiple tokens is a problem and it gives flexibility for individuals that have some of one token and not another. 

    b) Adding an exchange rate for tokens requires further config actions by the DAO to set the exchange rate for each token (using an Oracle would require a bit more research, and I'm unsure how rates would be set for tokens that aren't widely used). So I think it's a toss up between the DAO specifying the exchange rate or the user. Either way the UI should suggest an amount to whoever is creating the token request, but of course this doesn't reduce the need for voters to cross check it with the current rate when they can specify any amount.

3) @rperez89 and I have discussed this previously. Unfortunately I'm not sure if we can reliably know whether a token request is still being voted on or if the vote for it has finalised. This requires more research and is a front-end task. The reason for the storage layout you have described is so we know which `TokenRequest`'s belong to which user so we can find them easily. As a side note, the reason we have two mappings, instead of one `mapping(address => TokenRequest[])` is to enable us to change the `TokenRequest` struct structure when the contract is upgraded without overwriting data.

**Comment by lkngtn** [comment]
The exchange rate thing is definitely not appropriate for this application, the requirement that the org evaluate each request individually is actually intended. The moloch like mechanism depends on membership being “permissioned”, which requires each request be evaluated individually. 

It’s not intended to be used as a permissionless token sale (which could be a useful app, but is not this app).

**Comment by lkngtn** [comment]
Going to close this since I think everything has been addressed and there are no clear action items. In the future I think it would be better to create individual issues for each topic as it is a bit confusing to follow this thread.
