### ISSUE TITLE
Include more information about the request to voters

### ISSUE THREAD

**Issue by lkngtn** [1Hive/token-request-app#56]
When reviewing a token request voters will see something like: 

> Token Request: Finalise the token request with id 0, minting the requester funds and moving payment to the vault.

This doesn't provide much context for them to make the determination, it would be better if we could pull the requester's address, amount requested, and payment into the description. 

If we can't, perhaps we should implement a request detail page and link to it? 

I don't think its reasonable to expect that voters will go to the token request app, cross reference the id to find the info, and then use that to vote. (instead they will just use moloch 👹 🙈)

**Comment by rperez89** [comment]
Right now we can not do like this with the radspec, @fabriziovigevani is talking with Brett to se if we can modify the radspec to support that kind of things

**Comment by lkngtn** [comment]
> Right now we can not do like this with the radspec, @fabriziovigevani is talking with Brett to se if we can modify the radspec to support that kind of things

Makes sense, and I expected that was the case -- but feel like this is something worth pushing on even if we can't fix it right now. 

@onbjerg do you have any thoughts regarding this radspec challenge?

**Comment by onbjerg** [comment]
So the primary issue with Radspec here is that support for multiple return values for calls was never implemented and was in fact the first issue I created in the repository as well (https://github.com/aragon/radspec/issues/1).

It is possible to add support for this, and I think a lot of people would appreciate it as well. Things that the implementer would have to do are:

- **Determine what the syntax**. What should multiple return values look like? Right now, performing a call looks something like `addr.func(): type`, so it might look like `addr.func(): (type1, type2)` and then you would be able to access a value using `[index]` like JavaScript arrays or `.index` like Rust tuples.
- **Add the new syntax to the parser**. Depending on what the syntax should be like, the implementer can probably reuse existing tokens and add the logic [here](https://github.com/aragon/radspec/blob/master/src/parser/index.js#L278-L295).
- **Add support in the evaluator**. This should go somewhere around [here](https://github.com/aragon/radspec/blob/master/src/evaluator/index.js#L228).

I'd guesstimate, without having looked at the Radspec source since the initial-ish implementation, that it would probably take about 1-3 hours of work for someone familiar with the Radspec interpreter or with interpreters in general to implement, and for someone with good knowledge of how programming languages work it would probably take 2-4 hours.

**Comment by lkngtn** [comment]
> I'd guesstimate, without having looked at the Radspec source since the initial-ish implementation, that it would probably take about 1-3 hours of work for someone familiar with the Radspec interpreter or with interpreters in general to implement, and for someone with good knowledge of how programming languages work it would probably take 2-4 hours.

My guestimate is that this is optimistic :) 

If we were to submit a PR to radspec to fix this upstream, what would the process be like getting it included so that it is useful for us? I'm assuming we would need it first merged into radspec, then a change in aragon/aragon merged to include the new version of radspec, and only then it would be useable for token-request?

**Comment by onbjerg** [comment]
Yeah it has to be merged in to Radspec, then Aragon.js and then the client needs to update Aragon.js

**Comment by lkngtn** [comment]
Related to #62

**Comment by lkngtn** [comment]
I believe this can be closed. Feel free to re-open if I'm mistaken.
